// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOIOdlGEr27-YC4oeIINBTZ6j9tNfROY',
    appId: '1:50583172701:web:4269a114af2d04840effb4',
    messagingSenderId: '50583172701',
    projectId: 'veerangana-a8a70',
    authDomain: 'veerangana-a8a70.firebaseapp.com',
    storageBucket: 'veerangana-a8a70.firebasestorage.app',
    measurementId: 'G-C7YX7QYSKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-9mLUwtQmHd9KsPE2xS5_PlVM3B1KhM',
    appId: '1:50583172701:android:0ae02ec812a8171d0effb4',
    messagingSenderId: '50583172701',
    projectId: 'veerangana-a8a70',
    storageBucket: 'veerangana-a8a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDNcdjxG4AzerGA4m7RLPWnNxbvfgOiM',
    appId: '1:50583172701:ios:64feb503c993c02f0effb4',
    messagingSenderId: '50583172701',
    projectId: 'veerangana-a8a70',
    storageBucket: 'veerangana-a8a70.firebasestorage.app',
    iosBundleId: 'com.example.veerangana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWDNcdjxG4AzerGA4m7RLPWnNxbvfgOiM',
    appId: '1:50583172701:ios:64feb503c993c02f0effb4',
    messagingSenderId: '50583172701',
    projectId: 'veerangana-a8a70',
    storageBucket: 'veerangana-a8a70.firebasestorage.app',
    iosBundleId: 'com.example.veerangana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOIOdlGEr27-YC4oeIINBTZ6j9tNfROY',
    appId: '1:50583172701:web:f9ffc33cf6da25680effb4',
    messagingSenderId: '50583172701',
    projectId: 'veerangana-a8a70',
    authDomain: 'veerangana-a8a70.firebaseapp.com',
    storageBucket: 'veerangana-a8a70.firebasestorage.app',
    measurementId: 'G-Y76VL9WJZ0',
  );
}
